version: '3'
services:
  db:
    build: ./db
    environment:
      - MYSQL_DATABASE=reviews
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3004:3004"
